#! /usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import codecs
import json
import datetime
from collections import OrderedDict

def printFbs(rootName, nameSpace, jsonData):
    print '// generated by json2fbs.py\n'

    # output namespace
    print 'namespace {0};\n'.format(nameSpace)

    # output tables
    for meta in jsonData["_meta"]:
        table_name = meta["name"]
        print 'table ' + table_name[0:1].upper() + table_name[1:] + " {"
        for item in jsonData[table_name]:
            print "    " + item["name"] + ":" + item["type"] + ";"
        print "}\n"

    print 'table ' + rootName[0:1].upper() + rootName[1:] + " {"
    for meta in jsonData["_meta"]:
        name = meta["name"]
        table_name = name[0:1].upper() + name[1:]
        if meta["type"] == "array":
            print "    " + name + ":[" + table_name + "];"
        else:
            print "    " + name + ":" + table_name + ";"
    print "}\n"

    # output root_type
    print 'root_type {0};'.format(rootName)

# ---
# root function
#
def json2fbs(jsonFile, rootName, nameSpace = ''):
    with open(jsonFile, 'r') as f:
        jsonData = json.loads(f.read(), object_pairs_hook=OrderedDict)
        if isinstance(jsonData, dict):
            printFbs(rootName, nameSpace, jsonData)
        else:
            print 'unsupported format. params:[{0}][{1}][{2}]'.format(jsonFile, rootName, nameSpace)

# ---
# default help message
#
def printHelp():
    print '''    need at least 2 args.
    __name__ json-file root-name [namespace]
    e.g. json2fbs.py master_schema.json Master test.mytest'''


# ---
# main function
#
if __name__ == '__main__':
    sys.stdout = codecs.lookup('utf_8')[-1](sys.stdout)
    argv = sys.argv
    argc = len(argv)
    if argc < 3:
        printHelp()
    elif argc < 4:
        json2fbs(argv[1],argv[2])
    else:
        json2fbs(argv[1],argv[2],argv[3])
